### ISSUE TITLE
Deep sleep script missing

### ISSUE THREAD

**Issue by shonilchi** [DevilDipan/adbdebloater_opseries#5]
Hi,  could you please re-post the script which is missing at https://github.com/themagicalmammal/oos_debloater/blob/master/deepsleepscript.txt

**Comment by themagicalmammal** [comment]
It was deprecated due to being buggy.
But you can check it [here](https://github.com/themagicalmammal/oos_debloater/blob/8333a82edbaf1162b0f6cd87680073c57e909674/deepsleepscript.txt).
This only works with Oneplus 7 and lower if you have bugs reboot it will fix it.

**Comment by shonilchi** [comment]
> It was deprecated due to being buggy.
> But you can check it [here](https://github.com/themagicalmammal/oos_debloater/blob/8333a82edbaf1162b0f6cd87680073c57e909674/deepsleepscript.txt).
> This only works with Oneplus 7 and lower if you have bugs reboot it will fix it.

Thanks, I have a oneplus 7 and have just run this.

**Comment by themagicalmammal** [comment]
Yeah No Problem
